CREATE TABLE "_ReadLinks" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,
    CONSTRAINT "_ReadLinks_AB_pkey" PRIMARY KEY ("A", "B")
);

CREATE INDEX "_ReadLinks_B_index" ON "_ReadLinks"("B");
ALTER TABLE "_ReadLinks" ADD CONSTRAINT "_ReadLinks_A_fkey" FOREIGN KEY ("A") REFERENCES "Link"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_ReadLinks" ADD CONSTRAINT "_ReadLinks_B_fkey" FOREIGN KEY ("B") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
